# Bag of word

In [1]:
import numpy as np
import pandas as pd

In [4]:
df=pd.DataFrame({"text":["people watch Movie",
                         "people watch cricket",
                         "people write comment",
                          "i write comment"],"output":[1,1,0,0]})

In [5]:
df

text  output
0    people watch Movie       1
1  people watch cricket       1
2  people write comment       0
3       i write comment       0

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [7]:
bow=cv.fit_transform(df['text'])

In [8]:
print(cv.vocabulary_)

{'people': 3, 'watch': 4, 'movie': 2, 'cricket': 1, 'write': 5, 'comment': 0}


In [9]:
bow.toarray()

array([[0, 0, 1, 1, 1, 0],
       [0, 1, 0, 1, 1, 0],
       [1, 0, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 1]], dtype=int64)

In [11]:
cv.transform(['I watch cricket']).toarray()

array([[0, 1, 0, 0, 1, 0]], dtype=int64)

In [13]:
x=bow.toarray()
y=df['output']

In [14]:
x

array([[0, 0, 1, 1, 1, 0],
       [0, 1, 0, 1, 1, 0],
       [1, 0, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 1]], dtype=int64)

In [15]:
y

0    1
1    1
2    0
3    0
Name: output, dtype: int64

# N-Grams

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

In [17]:
cv=CountVectorizer(ngram_range=(2,2))

In [18]:
bow=cv.fit_transform(df['text'])

In [19]:
print(cv.vocabulary_)

{'people watch': 0, 'watch movie': 3, 'watch cricket': 2, 'people write': 1, 'write comment': 4}


# TF-IDF (Term frequency- Inverse document frequency)

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid=TfidfVectorizer()

In [21]:
arr=tfid.fit_transform(df['text'])

In [22]:
arr

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 11 stored elements and shape (4, 6)>

In [23]:
arr.toarray()

array([[0.        , 0.        , 0.70203482, 0.44809973, 0.55349232,
        0.        ],
       [0.        , 0.70203482, 0.        , 0.44809973, 0.55349232,
        0.        ],
       [0.61366674, 0.        , 0.        , 0.49681612, 0.        ,
        0.61366674],
       [0.70710678, 0.        , 0.        , 0.        , 0.        ,
        0.70710678]])